# -*- coding: utf-8 -*-
"""Customer Personality Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AhjkWPBafpmE51T4-l77NxBMHn5rWhHH

# **Import Essential Libraries**

### First we wiil import all the libraries that we will use in our project.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""# **Load the Dataset**"""

df=pd.read_csv('marketing_campaign.csv', sep='\t')
df.head()

"""## **Dataset Information Summary**


"""

df.info()

"""<span style="font-size: 18px; font-weight: bold;">distribution of customer education level¶
.</span>

### **Distribution of Education Level**
"""

education_level_distribution = df['Education'].value_counts()
education_level_distribution

"""# **Bar Plot of Education Level Distribution**"""

plt.figure(figsize=(10,6))
df['Education'].value_counts().plot(kind='bar', color='lightpink')
plt.title('Education Level Distribution')
plt.xlabel('Education Level')
plt.ylabel('Number of Customers')
plt.show()

"""<span style="font-size: 18px; font-weight: bold;">What is the age distribution of customers?
.</span>

# **Histogram of Customer Age Distribution**
"""

plt.figure(figsize=(10,6))
df['Year_Birth'].plot(kind='hist', bins=20, color='pink',edgecolor='black')
plt.title('Age Distribution')
plt.xlabel('Year of Birth')
plt.ylabel('Frequency')
plt.show()

"""<span style="font-size: 18px; font-weight: bold;">What is the average annual income of customers?
.</span>

# **Calculating Average Customer Income**
"""

average_income = df['Income'].mean()
print(f'Average Income: {average_income}')

"""<span style="font-size: 18px; font-weight: bold;">What are the most frequently purchased products (wine, fruits, meat products, etc.)?
.</span>

### **Total Spending on Different Product Categories**
"""

products = ['MntWines', 'MntFruits', 'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts', 'MntGoldProds']
total_spent = df[products].sum()
plt.figure(figsize=(10,6))
total_spent.plot(kind='bar', color='salmon')
plt.title('Total Spending on Products')
plt.xlabel('Products')
plt.ylabel('Total Spending')
plt.show()

"""<span style="font-size: 18px; font-weight: bold;">How does the rate of spending on products differ between different age groups?
.</span>

### **Analysis of Average Product Spending by Age Group**
"""

df['Age'] = 2024 - df['Year_Birth']
age_bins = [20, 30, 40, 50, 60, 70, 80, 90]
df['Age_Group'] = pd.cut(df['Age'], bins=age_bins)

spending_by_age = df.groupby('Age_Group')[products].mean()
spending_by_age.plot(kind='bar', figsize=(14,8))
plt.title('Average Spending on Products by Age Group')
plt.xlabel('Age Group')
plt.ylabel('Average Spending')
plt.show()

"""<span style="font-size: 18px; font-weight: bold;">Is there a difference in spending rate between married and single customers?
.</span>

### **Analysis of Average Product Spending by Marital Status**
"""

spending_by_marital_status = df.groupby('Marital_Status')[products].mean()
spending_by_marital_status.plot(kind='bar', figsize=(14,8))
plt.title('Average Spending on Products by Marital Status')
plt.xlabel('Marital Status')
plt.ylabel('Average Spending')
plt.show()

"""<span style="font-size: 18px; font-weight: bold;">Is the rate of purchasing online different from purchasing in stores?
.</span>

### **Comparison of Total Purchases: Online vs In-Store**
"""

df['Total_Online_Purchases'] = df['NumWebPurchases'] + df['NumCatalogPurchases']
df['Total_Store_Purchases'] = df['NumStorePurchases']

online_vs_store = df[['Total_Online_Purchases', 'Total_Store_Purchases']].sum()
plt.figure(figsize=(10,6))
online_vs_store.plot(kind='bar', color=['Pink', 'yellow'])
plt.title('Total Purchases: Online vs Store')
plt.xlabel('Purchase Type')
plt.ylabel('Total Purchases')
plt.show()

"""<span style="font-size: 18px; font-weight: bold;">Is there a relationship between a customer's income and the number of online purchases?

.</span>

### **Scatter Plot of Income vs Total Online Purchases**
"""

plt.figure(figsize=(10,6))
plt.scatter(df['Income'], df['Total_Online_Purchases'], alpha=0.5, color='pink')
plt.title('Income vs Online Purchases')
plt.xlabel('Income')
plt.ylabel('Total Online Purchases')
plt.show()

"""<span style="font-size: 18px; font-weight: bold;">What is the relationship between age and the number of monthly visits to the site?


.</span>

### **Scatter Plot of Age vs Monthly Website Visits**
"""

plt.figure(figsize=(10,6))
plt.scatter(df['Age'], df['NumWebVisitsMonth'], alpha=0.5, color='red')
plt.title('Age vs Number of Website Visits per Month')
plt.xlabel('Age')
plt.ylabel('Number of Website Visits per Month')
plt.show()

"""<span style="font-size: 18px; font-weight: bold;">What factors affect customer acceptance of promotional offers?
.</span>

### **Box Plots of Income and Age vs Promotion Response**
"""

plt.figure(figsize=(14,8))
sns.boxplot(x='Response', y='Income', data=df)
plt.title('Income vs Promotion Response')
plt.xlabel('Response')
plt.ylabel('Income')
plt.show()

plt.figure(figsize=(14,8))
sns.boxplot(x='Response', y='Age', data=df)
plt.title('Age vs Promotion Response')
plt.xlabel('Response')
plt.ylabel('Age')
plt.show()

"""<span style="font-size: 18px; font-weight: bold;">What factors affect customer complaints?

.</span>

### **Box Plots of Income and Age vs Customer Complaints**
"""

plt.figure(figsize=(14,8))
sns.boxplot(x='Complain', y='Income', data=df)
plt.title('Income vs Customer Complaints')
plt.xlabel('Complain')
plt.ylabel('Income')
plt.show()

plt.figure(figsize=(14,8))
sns.boxplot(x='Complain', y='Age', data=df)
plt.title('Age vs Customer Complaints')
plt.xlabel('Complain')
plt.ylabel('Age')
plt.show()

"""<span style="font-size: 18px; font-weight: bold;">What is the promotion acceptance rate (cmp) for each age group?
.</span>

### **Promotional Offer Acceptance Rates by Age Group**
"""

response_by_age_group = df.groupby('Age_Group')[['AcceptedCmp1', 'AcceptedCmp2', 'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5']].mean()
response_by_age_group.plot(kind='bar', figsize=(14,8))
plt.title('Acceptance of Promotional Offers by Age Group')
plt.xlabel('Age Group')
plt.ylabel('Acceptance Rate')
plt.show()

"""<span style="font-size: 18px; font-weight: bold;">Is there a relationship between complaints and acceptance of promotions?

.</span>

### **Relationship Between Customer Complaints and Campaign Acceptance**
"""

acceptance_columns = ['AcceptedCmp1', 'AcceptedCmp2', 'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5']
df['Total_Accepted_Cmp'] = df[acceptance_columns].sum(axis=1)

plt.figure(figsize=(10,6))
plt.scatter(df['Complain'], df['Total_Accepted_Cmp'], alpha=0.5, color='purple')
plt.title('Complaints vs Total Accepted Campaigns')
plt.xlabel('Complain')
plt.ylabel('Total Accepted Campaigns')
plt.show()